_wandb:
    value:
        cli_version: 0.23.1
        code_path: code/train_wan22_stage2_finetune.py
        e:
            d9jay3q4ryq0m5j7x4865oaikxp618e8:
                args:
                    - --dataset_base_path
                    - /nyx-storage1/hanliu/Sim_Physics/TestOutput
                    - --dataset_metadata_path
                    - /home/mzh1800/DiffSynth-Studio/data/sim_physics_metadata.csv
                    - --dataset_repeat
                    - "500"
                    - --height
                    - "480"
                    - --width
                    - "480"
                    - --num_frames
                    - "49"
                    - --model_paths
                    - '["/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/models_t5_umt5-xxl-enc-bf16.pth", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/Wan2.2_VAE.pth"]'
                    - --tokenizer_path
                    - /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/google/umt5-xxl
                    - --output_path
                    - /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage2_finetune_spatio_depth_full
                    - --finetune_mode
                    - custom
                    - --trainable_param_patterns
                    - blocks\.12\.|blocks\.13\.|blocks\.14\.|blocks\.21\.|blocks\.22\.|blocks\.23\.
                    - --trainable_scope
                    - dit
                    - --save_modules
                    - dit
                    - --motion_channels
                    - "4"
                    - --motion_head_checkpoint
                    - /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage1_spatio_depth_full/final/motion_head.pth
                    - --depth_head_checkpoint
                    - /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage1_spatio_depth_full/final/depth_head.pth
                    - --motion_loss_weight
                    - "0.5"
                    - --depth_loss_weight
                    - "0.5"
                    - --learning_rate
                    - "1e-5"
                    - --num_epochs
                    - "10"
                    - --batch_size
                    - "1"
                    - --gradient_accumulation_steps
                    - "8"
                    - --save_steps
                    - "500"
                    - --use_warp_loss
                    - --warp_loss_weight
                    - "0.1"
                    - --warp_loss_type
                    - mse
                    - --use_rgb_warp_loss
                    - --rgb_warp_loss_weight
                    - "0.1"
                    - --rgb_warp_loss_type
                    - l1
                    - --use_wandb
                    - --wandb_project
                    - wan22-ti2v-stage2-finetune
                    - --wandb_name
                    - wan22-ti2v-stage2-finetune-spatio-depth-full
                    - --use_spatiotemporal_depth
                    - --spatiotemporal_depth_type
                    - full
                codePath: train_wan22_stage2_finetune.py
                codePathLocal: train_wan22_stage2_finetune.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "52403109888"
                        used: "1325817856"
                email: swu@u.northwestern.edu
                executable: /nyx-storage1/hanliu/miniconda3/envs/diffsyn/bin/python3.10
                git:
                    commit: 6704417fecd8d59e448f11602e9e3161969656dc
                    remote: https://github.com/Windsao/Sim4VideoGen.git
                gpu: NVIDIA A40
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-aec1446c-76cd-43ef-63fd-179ad68f1806
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-0dfaee79-a37e-0666-556f-c66e1ae3c4fa
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-97cad36c-c9a2-4c1f-a142-38a1b39c89f0
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-157261bc-52e8-c593-39b7-55d0b91873eb
                host: hemera.cs.northwestern.edu
                memory:
                    total: "404373397504"
                os: Linux-4.18.0-553.89.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /home/mzh1800/DiffSynth-Studio/train_wan22_stage2_finetune.py
                python: CPython 3.10.18
                root: /home/mzh1800/DiffSynth-Studio
                slurm:
                    cluster_name: pardo
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "48"
                    cpus_per_task: "48"
                    distribution: cyclic
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: mzh1800
                    job_cpus_per_node: "48"
                    job_end_time: "1798043667"
                    job_gid: "1017"
                    job_group: mzh1800
                    job_id: "13851"
                    job_name: bash
                    job_nodelist: hemera
                    job_num_nodes: "1"
                    job_partition: all
                    job_qos: normal
                    job_start_time: "1766507667"
                    job_uid: "1016"
                    job_user: mzh1800
                    jobid: "13851"
                    launch_node_ipaddr: 165.124.149.118
                    localid: "0"
                    mem_per_node: "358400"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: hemera
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "45735"
                    pty_win_col: "370"
                    pty_win_row: "35"
                    srun_comm_host: 165.124.149.118
                    srun_comm_port: "37123"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "37123"
                    step_nodelist: hemera
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/mzh1800
                    submit_host: slurm01.cs.northwestern.edu
                    task_pid: "10164"
                    tasks_per_node: "1"
                    topology_addr: hemera
                    topology_addr_pattern: node
                    umask: "0002"
                    working_cluster: pardo:165.124.149.118:6817:9984:109
                startedAt: "2025-12-23T16:48:14.109385Z"
                writerId: d9jay3q4ryq0m5j7x4865oaikxp618e8
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.23.1
            "6": 4.56.2
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 1
dataset_base_path:
    value: /nyx-storage1/hanliu/Sim_Physics/TestOutput
dataset_metadata_path:
    value: /home/mzh1800/DiffSynth-Studio/data/sim_physics_metadata.csv
dataset_repeat:
    value: 500
depth_head_checkpoint:
    value: /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage1_spatio_depth_full/final/depth_head.pth
depth_loss_type:
    value: mse
depth_loss_weight:
    value: 0.5
extra_inputs:
    value: input_image
finetune_mode:
    value: custom
gradient_accumulation_steps:
    value: 8
height:
    value: 480
learning_rate:
    value: 1e-05
lora_checkpoint:
    value: null
lora_rank:
    value: 32
lora_target_modules:
    value: q,k,v,o,ffn.0,ffn.2
model_id_with_origin_paths:
    value: null
model_paths:
    value: '[["/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/diffusion_pytorch_model-00001-of-00003-bf16.safetensors", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/diffusion_pytorch_model-00002-of-00003-bf16.safetensors", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/diffusion_pytorch_model-00003-of-00003-bf16.safetensors"], "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/models_t5_umt5-xxl-enc-bf16.pth", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/Wan2.2_VAE.pth"]'
motion_channels:
    value: 4
motion_head_checkpoint:
    value: /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage1_spatio_depth_full/final/motion_head.pth
motion_loss_type:
    value: mse
motion_loss_weight:
    value: 0.5
num_epochs:
    value: 10
num_frames:
    value: 49
output_path:
    value: /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage2_finetune_spatio_depth_full
rgb_warp_loss_type:
    value: l1
rgb_warp_loss_weight:
    value: 0.1
rgb_warp_ssim_weight:
    value: 0.85
rgb_warp_use_ssim:
    value: false
save_modules:
    value: dit
save_steps:
    value: 500
save_trainable_only:
    value: false
spatiotemporal_depth_type:
    value: full
tokenizer_path:
    value: /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/google/umt5-xxl
trainable_models:
    value: dit
trainable_param_patterns:
    value: blocks\.12\.|blocks\.13\.|blocks\.14\.|blocks\.21\.|blocks\.22\.|blocks\.23\.
trainable_scope:
    value: dit
use_rgb_warp_loss:
    value: true
use_spatiotemporal_depth:
    value: true
use_wandb:
    value: true
use_warp_loss:
    value: true
wandb_name:
    value: wan22-ti2v-stage2-finetune-spatio-depth-full
wandb_project:
    value: wan22-ti2v-stage2-finetune
warp_loss_type:
    value: mse
warp_loss_weight:
    value: 0.1
width:
    value: 480
